### ISSUE TITLE
Benefits not showing

### ISSUE THREAD

**Issue by vanillaiice** [felicianotech/hugo-theme-lean-launch-page#30]
Hi, I followed the project layout in the exampleSite folder to make a site. Everything is working as expected (social media links, title, tagline, footer), except the benefits.

Here is the the layout of my content folder:
```sh
content/
├── benefits
│   ├── benefit-1.md
│   ├── benefit-2.md
│   └── benefit-3.md
└── footer.md
```

The actual content of the benefits files:
benefit-1.md:
```md
+++
title = 'Reason 1'
icon = "fa-users"
weight = 1
+++
#Reason one

- foo
- bar
```

benefit-2.md
```md
+++
title = "Benefit 2"
icon = "fa-shield"
weight = 2
+++
Another benefit. Really tell people why they NEED to get this thing. Why is it better?
```

benefit-3.md
```md
+++
title = "Sign Up Today"
icon = "fa-paper-plane"
weight = 3
+++
Provide a call-to-action (CTA) to Sign up with the MailChimp form. If you're not using MailChimp, then this is Benefit 3.
```

here is my hugo.toml config:
```toml
baseURL = 'https://itpg.cc/'
languageCode = 'en-us'
title = 'Title'
author = "vanillaiice"
theme = 'lean-launch-page'
paginate = 3
canonifyurls = true

[params]
tagline = "tagline"
twitter = "https://twitter.com/_itpg"
github = "https://github.com/vanillaiice/itpg-frontend"
```
